-- Auto-generated from skills.txt
-- Seeds the skills table for the SkillExtractor

INSERT INTO skills (skill_name) VALUES ('Java');
INSERT INTO skills (skill_name) VALUES ('Python');
INSERT INTO skills (skill_name) VALUES ('C');
INSERT INTO skills (skill_name) VALUES ('C++');
INSERT INTO skills (skill_name) VALUES ('C#');
INSERT INTO skills (skill_name) VALUES ('JavaScript');
INSERT INTO skills (skill_name) VALUES ('TypeScript');
INSERT INTO skills (skill_name) VALUES ('PHP');
INSERT INTO skills (skill_name) VALUES ('Go');
INSERT INTO skills (skill_name) VALUES ('Rust');
INSERT INTO skills (skill_name) VALUES ('Kotlin');
INSERT INTO skills (skill_name) VALUES ('Swift');
INSERT INTO skills (skill_name) VALUES ('Spring Boot');
INSERT INTO skills (skill_name) VALUES ('Hibernate');
INSERT INTO skills (skill_name) VALUES ('JPA');
INSERT INTO skills (skill_name) VALUES ('React');
INSERT INTO skills (skill_name) VALUES ('Angular');
INSERT INTO skills (skill_name) VALUES ('Vue.js');
INSERT INTO skills (skill_name) VALUES ('Node.js');
INSERT INTO skills (skill_name) VALUES ('Express.js');
INSERT INTO skills (skill_name) VALUES ('Docker');
INSERT INTO skills (skill_name) VALUES ('Kubernetes');
INSERT INTO skills (skill_name) VALUES ('Git');
INSERT INTO skills (skill_name) VALUES ('GitHub');
INSERT INTO skills (skill_name) VALUES ('Jenkins');
INSERT INTO skills (skill_name) VALUES ('REST API');
INSERT INTO skills (skill_name) VALUES ('GraphQL');
INSERT INTO skills (skill_name) VALUES ('Microservices');
INSERT INTO skills (skill_name) VALUES ('Machine Learning');
INSERT INTO skills (skill_name) VALUES ('Deep Learning');
INSERT INTO skills (skill_name) VALUES ('Artificial Intelligence');
INSERT INTO skills (skill_name) VALUES ('Data Science');
INSERT INTO skills (skill_name) VALUES ('Natural Language Processing');
INSERT INTO skills (skill_name) VALUES ('Computer Vision');
INSERT INTO skills (skill_name) VALUES ('TensorFlow');
INSERT INTO skills (skill_name) VALUES ('PyTorch');
INSERT INTO skills (skill_name) VALUES ('Scikit-Learn');
INSERT INTO skills (skill_name) VALUES ('Pandas');
INSERT INTO skills (skill_name) VALUES ('NumPy');
INSERT INTO skills (skill_name) VALUES ('Data Analytics');
INSERT INTO skills (skill_name) VALUES ('Big Data');
INSERT INTO skills (skill_name) VALUES ('Apache Spark');
INSERT INTO skills (skill_name) VALUES ('Hadoop');
INSERT INTO skills (skill_name) VALUES ('Tableau');
INSERT INTO skills (skill_name) VALUES ('Power BI');
INSERT INTO skills (skill_name) VALUES ('MySQL');
INSERT INTO skills (skill_name) VALUES ('PostgreSQL');
INSERT INTO skills (skill_name) VALUES ('MongoDB');
INSERT INTO skills (skill_name) VALUES ('Oracle');
INSERT INTO skills (skill_name) VALUES ('SQL Server');
INSERT INTO skills (skill_name) VALUES ('SQLite');
INSERT INTO skills (skill_name) VALUES ('Redis');
INSERT INTO skills (skill_name) VALUES ('Cassandra');
INSERT INTO skills (skill_name) VALUES ('AWS');
INSERT INTO skills (skill_name) VALUES ('Azure');
INSERT INTO skills (skill_name) VALUES ('Google Cloud Platform');
INSERT INTO skills (skill_name) VALUES ('EC2');
INSERT INTO skills (skill_name) VALUES ('S3');
INSERT INTO skills (skill_name) VALUES ('Lambda');
INSERT INTO skills (skill_name) VALUES ('Terraform');
INSERT INTO skills (skill_name) VALUES ('Ansible');
INSERT INTO skills (skill_name) VALUES ('CI/CD');
INSERT INTO skills (skill_name) VALUES ('Linux');
INSERT INTO skills (skill_name) VALUES ('Shell Scripting');
INSERT INTO skills (skill_name) VALUES ('Ethical Hacking');
INSERT INTO skills (skill_name) VALUES ('Penetration Testing');
INSERT INTO skills (skill_name) VALUES ('Network Security');
INSERT INTO skills (skill_name) VALUES ('Cyber Security');
INSERT INTO skills (skill_name) VALUES ('Vulnerability Assessment');
INSERT INTO skills (skill_name) VALUES ('Incident Response');
INSERT INTO skills (skill_name) VALUES ('SIEM');
INSERT INTO skills (skill_name) VALUES ('Cryptography');
INSERT INTO skills (skill_name) VALUES ('Cisco');
INSERT INTO skills (skill_name) VALUES ('CCNA');
INSERT INTO skills (skill_name) VALUES ('Routing');
INSERT INTO skills (skill_name) VALUES ('Switching');
INSERT INTO skills (skill_name) VALUES ('TCP/IP');
INSERT INTO skills (skill_name) VALUES ('DNS');
INSERT INTO skills (skill_name) VALUES ('DHCP');
INSERT INTO skills (skill_name) VALUES ('Firewall');
INSERT INTO skills (skill_name) VALUES ('VPN');
INSERT INTO skills (skill_name) VALUES ('AutoCAD');
INSERT INTO skills (skill_name) VALUES ('SolidWorks');
INSERT INTO skills (skill_name) VALUES ('CATIA');
INSERT INTO skills (skill_name) VALUES ('ANSYS');
INSERT INTO skills (skill_name) VALUES ('MATLAB');
INSERT INTO skills (skill_name) VALUES ('PLC');
INSERT INTO skills (skill_name) VALUES ('CNC');
INSERT INTO skills (skill_name) VALUES ('Manufacturing');
INSERT INTO skills (skill_name) VALUES ('Lean Manufacturing');
INSERT INTO skills (skill_name) VALUES ('Six Sigma');
INSERT INTO skills (skill_name) VALUES ('Quality Control');
INSERT INTO skills (skill_name) VALUES ('AutoCAD Civil 3D');
INSERT INTO skills (skill_name) VALUES ('STAAD Pro');
INSERT INTO skills (skill_name) VALUES ('ETABS');
INSERT INTO skills (skill_name) VALUES ('Revit');
INSERT INTO skills (skill_name) VALUES ('Surveying');
INSERT INTO skills (skill_name) VALUES ('Quantity Estimation');
INSERT INTO skills (skill_name) VALUES ('Construction Management');
INSERT INTO skills (skill_name) VALUES ('Structural Analysis');
INSERT INTO skills (skill_name) VALUES ('Power Systems');
INSERT INTO skills (skill_name) VALUES ('PLC');
INSERT INTO skills (skill_name) VALUES ('SCADA');
INSERT INTO skills (skill_name) VALUES ('Embedded Systems');
INSERT INTO skills (skill_name) VALUES ('VLSI');
INSERT INTO skills (skill_name) VALUES ('Circuit Design');
INSERT INTO skills (skill_name) VALUES ('MATLAB');
INSERT INTO skills (skill_name) VALUES ('Electrical Maintenance');
INSERT INTO skills (skill_name) VALUES ('Arduino');
INSERT INTO skills (skill_name) VALUES ('Raspberry Pi');
INSERT INTO skills (skill_name) VALUES ('Embedded C');
INSERT INTO skills (skill_name) VALUES ('Microcontrollers');
INSERT INTO skills (skill_name) VALUES ('PCB Design');
INSERT INTO skills (skill_name) VALUES ('IoT');
INSERT INTO skills (skill_name) VALUES ('FPGA');
INSERT INTO skills (skill_name) VALUES ('Patient Care');
INSERT INTO skills (skill_name) VALUES ('Clinical Research');
INSERT INTO skills (skill_name) VALUES ('Medical Coding');
INSERT INTO skills (skill_name) VALUES ('Phlebotomy');
INSERT INTO skills (skill_name) VALUES ('Nursing');
INSERT INTO skills (skill_name) VALUES ('Electronic Health Records');
INSERT INTO skills (skill_name) VALUES ('Healthcare Management');
INSERT INTO skills (skill_name) VALUES ('Tally');
INSERT INTO skills (skill_name) VALUES ('GST');
INSERT INTO skills (skill_name) VALUES ('Taxation');
INSERT INTO skills (skill_name) VALUES ('Financial Analysis');
INSERT INTO skills (skill_name) VALUES ('Bookkeeping');
INSERT INTO skills (skill_name) VALUES ('Auditing');
INSERT INTO skills (skill_name) VALUES ('QuickBooks');
INSERT INTO skills (skill_name) VALUES ('SAP FICO');
INSERT INTO skills (skill_name) VALUES ('Investment Analysis');
INSERT INTO skills (skill_name) VALUES ('Recruitment');
INSERT INTO skills (skill_name) VALUES ('Talent Acquisition');
INSERT INTO skills (skill_name) VALUES ('Payroll Management');
INSERT INTO skills (skill_name) VALUES ('Employee Relations');
INSERT INTO skills (skill_name) VALUES ('Performance Management');
INSERT INTO skills (skill_name) VALUES ('HR Analytics');
INSERT INTO skills (skill_name) VALUES ('Onboarding');
INSERT INTO skills (skill_name) VALUES ('Digital Marketing');
INSERT INTO skills (skill_name) VALUES ('SEO');
INSERT INTO skills (skill_name) VALUES ('SEM');
INSERT INTO skills (skill_name) VALUES ('Google Ads');
INSERT INTO skills (skill_name) VALUES ('Social Media Marketing');
INSERT INTO skills (skill_name) VALUES ('Content Marketing');
INSERT INTO skills (skill_name) VALUES ('Email Marketing');
INSERT INTO skills (skill_name) VALUES ('Lead Generation');
INSERT INTO skills (skill_name) VALUES ('Sales Management');
INSERT INTO skills (skill_name) VALUES ('CRM');
INSERT INTO skills (skill_name) VALUES ('Project Management');
INSERT INTO skills (skill_name) VALUES ('Agile');
INSERT INTO skills (skill_name) VALUES ('Scrum');
INSERT INTO skills (skill_name) VALUES ('Kanban');
INSERT INTO skills (skill_name) VALUES ('Business Analysis');
INSERT INTO skills (skill_name) VALUES ('Strategic Planning');
INSERT INTO skills (skill_name) VALUES ('Operations Management');
INSERT INTO skills (skill_name) VALUES ('Risk Management');
INSERT INTO skills (skill_name) VALUES ('UI Design');
INSERT INTO skills (skill_name) VALUES ('UX Design');
INSERT INTO skills (skill_name) VALUES ('Figma');
INSERT INTO skills (skill_name) VALUES ('Adobe Photoshop');
INSERT INTO skills (skill_name) VALUES ('Adobe Illustrator');
INSERT INTO skills (skill_name) VALUES ('Adobe XD');
INSERT INTO skills (skill_name) VALUES ('Canva');
INSERT INTO skills (skill_name) VALUES ('Graphic Design');
INSERT INTO skills (skill_name) VALUES ('Video Editing');
INSERT INTO skills (skill_name) VALUES ('Content Writing');
INSERT INTO skills (skill_name) VALUES ('Copywriting');
INSERT INTO skills (skill_name) VALUES ('Technical Writing');
INSERT INTO skills (skill_name) VALUES ('Blog Writing');
INSERT INTO skills (skill_name) VALUES ('Proofreading');
INSERT INTO skills (skill_name) VALUES ('Journalism');
INSERT INTO skills (skill_name) VALUES ('Public Relations');
INSERT INTO skills (skill_name) VALUES ('Teaching');
INSERT INTO skills (skill_name) VALUES ('Curriculum Development');
INSERT INTO skills (skill_name) VALUES ('Classroom Management');
INSERT INTO skills (skill_name) VALUES ('Lesson Planning');
INSERT INTO skills (skill_name) VALUES ('Student Assessment');
INSERT INTO skills (skill_name) VALUES ('Legal Research');
INSERT INTO skills (skill_name) VALUES ('Contract Drafting');
INSERT INTO skills (skill_name) VALUES ('Corporate Law');
INSERT INTO skills (skill_name) VALUES ('Compliance');
INSERT INTO skills (skill_name) VALUES ('Litigation');
INSERT INTO skills (skill_name) VALUES ('Hotel Management');
INSERT INTO skills (skill_name) VALUES ('Food & Beverage Service');
INSERT INTO skills (skill_name) VALUES ('Front Office Operations');
INSERT INTO skills (skill_name) VALUES ('Customer Service');
INSERT INTO skills (skill_name) VALUES ('Event Management');
INSERT INTO skills (skill_name) VALUES ('Inventory Management');
INSERT INTO skills (skill_name) VALUES ('Warehouse Management');
INSERT INTO skills (skill_name) VALUES ('Procurement');
INSERT INTO skills (skill_name) VALUES ('Logistics');
INSERT INTO skills (skill_name) VALUES ('Supply Chain Management');
INSERT INTO skills (skill_name) VALUES ('Demand Forecasting');
INSERT INTO skills (skill_name) VALUES ('Communication');
INSERT INTO skills (skill_name) VALUES ('Leadership');
INSERT INTO skills (skill_name) VALUES ('Problem Solving');
INSERT INTO skills (skill_name) VALUES ('Critical Thinking');
INSERT INTO skills (skill_name) VALUES ('Teamwork');
INSERT INTO skills (skill_name) VALUES ('Time Management');
INSERT INTO skills (skill_name) VALUES ('Presentation Skills');
INSERT INTO skills (skill_name) VALUES ('Negotiation');
INSERT INTO skills (skill_name) VALUES ('Decision Making');
INSERT INTO skills (skill_name) VALUES ('Adaptability');
